from knot import Knot, gendowkers

trefoil = Knot([6, -10, 12, 4, -8, 2, 14])
square = Knot([6, 8, 2, 4])
falsesquare = Knot([6, -8, -2, -4])
typeIIItrefoil = Knot([12, -16, -18, -14, 6, 4, 8, 2, -10])
impossible1 = Knot([4, 6, 8, 2])
lexographic1 = Knot([10, 6, 2, 4, 8, 12])
lexographic2 = Knot([4, 6, 2, 10, 12, 8])
comptrefoils = Knot([4, 12, 2, 10, 6, 8])
typeItrefoil = Knot([6, 4, 8, 2])
sixthree = Knot([4, 8, 10, 2, 12, 6])
sixone = Knot([4, 8, 12, 10, 2, 6])

print("Dowker Generation 3 crossings:\n", gendowkers(3))
print("\n")
print("Trefoil:", trefoil.dowker)
print("trefoilI:", trefoil.typeI())
print("trefoilII:", trefoil.typeII())
print("Trefoil:", trefoil.zeroremove())
print("\n")
print("Square:", square.dowker)
print("SquareI:", square.typeI())
print("SquareII:", square.typeII())
print("Square:", square.zeroremove())
print("\n")
print("False Sqaure:", falsesquare.dowker)
print("False SquareI:", falsesquare.typeI())
print("False SquareII:", falsesquare.typeII())
print("False Square:", falsesquare.zeroremove())
print("\n")
print("TypeIIItrefoil:", typeIIItrefoil.dowker)
print("TypeIIItrefoil III:", Knot.signflip(Knot(typeIIItrefoil.typeIII())))
print("TypeIIItrefoil:", typeIIItrefoil.zeroremove())
print("\n")
print("Impossible1:", impossible1.dowker)
var = impossible1.dowkerpossible()
if var == True:
     print("SquarePoss: True")
else:
     print("SquarePoss: False")
print("\n")
print("Lexographic1:", lexographic1.dowker)
var = lexographic1.DowkerIsLexographic()
if var == True:
     print("Lexographic1: True")
else:
     print("Lexographic1: False")
print("Lexographic2:", lexographic2.dowker)
var = lexographic2.DowkerIsLexographic()
if var == True:
     print("Lexographic2: True")
else:
     print("Lexographic2: False")
print("\n")
var = comptrefoils.prime()
if var == True:
     print("Comptrefoils: Prime")
else:
     print("Comptrefoils: Composite")
var = typeItrefoil.prime()
if var == True:
     print("TypeItrefoil: Prime")
else:
     print("TypeItrefoil: Composite")
var = square.prime()
if var == True:
     print("Square: Prime")
else:
     print("Square: Composite")
print("\n")
print("Square:", square.dowker)
print("SquareColor:", square.colorability())
print("\n")
print("6:3 knot flypes:", sixthree.flypedetect())
print("6:1 knot flypes:", sixone.flypedetect())
print("\n")
print("Make lexo:", [6, 8, 10, 2, 12, 4], "to", Knot.makelexographic(Knot([6, 8, 10, 2, 12, 4])))
print("\n")
print("**Six Three Flyping Tangle [2, 3], [7, 8] and Crossing 1**")
print("Six Three Before:")
print(sixthree.dowker)
print("Six Three After:")
print(Knot.performflype(sixthree, [[2, 3], [7, 8], 1]))